# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 6ace0de3f85f875f2980741c94adc9647eb03ad5b76eae48f3558d93ede526d5576434ccd5b7a0f2c473b13cecc769069da215e32112789956593295303b0a6f

test:
  secret_key_base: 039043501c18d654e7587f12a19f53c98ec17062ae82967e99de0820a32e03f150a2173ea4cb55fa38dd24f6458b07f25f846b82ef61ef7d36cdf7c119ee94d8

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
